// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: spectre.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMode int32

const (
	AgentMode_AGENT_MODE_UNSPECIFIED AgentMode = 0
	AgentMode_AGENT_MODE_SESSION     AgentMode = 1
	AgentMode_AGENT_MODE_BEACON      AgentMode = 2
)

// Enum value maps for AgentMode.
var (
	AgentMode_name = map[int32]string{
		0: "AGENT_MODE_UNSPECIFIED",
		1: "AGENT_MODE_SESSION",
		2: "AGENT_MODE_BEACON",
	}
	AgentMode_value = map[string]int32{
		"AGENT_MODE_UNSPECIFIED": 0,
		"AGENT_MODE_SESSION":     1,
		"AGENT_MODE_BEACON":      2,
	}
)

func (x AgentMode) Enum() *AgentMode {
	p := new(AgentMode)
	*p = x
	return p
}

func (x AgentMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentMode) Descriptor() protoreflect.EnumDescriptor {
	return file_spectre_proto_enumTypes[0].Descriptor()
}

func (AgentMode) Type() protoreflect.EnumType {
	return &file_spectre_proto_enumTypes[0]
}

func (x AgentMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentMode.Descriptor instead.
func (AgentMode) EnumDescriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{0}
}

type TaskType int32

const (
	TaskType_TASK_EXEC            TaskType = 0
	TaskType_TASK_SPECTRE_RECON   TaskType = 1
	TaskType_TASK_SPECTRE_SCAN    TaskType = 2
	TaskType_TASK_SPECTRE_FUZZ    TaskType = 3
	TaskType_TASK_SPECTRE_EXPLOIT TaskType = 4
	TaskType_TASK_PLUGIN          TaskType = 5
	TaskType_TASK_UPLOAD          TaskType = 6
	TaskType_TASK_DOWNLOAD        TaskType = 7
	TaskType_TASK_SHELL           TaskType = 8
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_EXEC",
		1: "TASK_SPECTRE_RECON",
		2: "TASK_SPECTRE_SCAN",
		3: "TASK_SPECTRE_FUZZ",
		4: "TASK_SPECTRE_EXPLOIT",
		5: "TASK_PLUGIN",
		6: "TASK_UPLOAD",
		7: "TASK_DOWNLOAD",
		8: "TASK_SHELL",
	}
	TaskType_value = map[string]int32{
		"TASK_EXEC":            0,
		"TASK_SPECTRE_RECON":   1,
		"TASK_SPECTRE_SCAN":    2,
		"TASK_SPECTRE_FUZZ":    3,
		"TASK_SPECTRE_EXPLOIT": 4,
		"TASK_PLUGIN":          5,
		"TASK_UPLOAD":          6,
		"TASK_DOWNLOAD":        7,
		"TASK_SHELL":           8,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_spectre_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_spectre_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{1}
}

type TaskOutputType int32

const (
	TaskOutputType_OUTPUT_RAW     TaskOutputType = 0
	TaskOutputType_OUTPUT_FINDING TaskOutputType = 1
	TaskOutputType_OUTPUT_TABLE   TaskOutputType = 2
	TaskOutputType_OUTPUT_FILE    TaskOutputType = 3
)

// Enum value maps for TaskOutputType.
var (
	TaskOutputType_name = map[int32]string{
		0: "OUTPUT_RAW",
		1: "OUTPUT_FINDING",
		2: "OUTPUT_TABLE",
		3: "OUTPUT_FILE",
	}
	TaskOutputType_value = map[string]int32{
		"OUTPUT_RAW":     0,
		"OUTPUT_FINDING": 1,
		"OUTPUT_TABLE":   2,
		"OUTPUT_FILE":    3,
	}
)

func (x TaskOutputType) Enum() *TaskOutputType {
	p := new(TaskOutputType)
	*p = x
	return p
}

func (x TaskOutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskOutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_spectre_proto_enumTypes[2].Descriptor()
}

func (TaskOutputType) Type() protoreflect.EnumType {
	return &file_spectre_proto_enumTypes[2]
}

func (x TaskOutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskOutputType.Descriptor instead.
func (TaskOutputType) EnumDescriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{2}
}

type EventType int32

const (
	EventType_EVENT_AGENT_CONNECTED    EventType = 0
	EventType_EVENT_AGENT_DISCONNECTED EventType = 1
	EventType_EVENT_TASK_STARTED       EventType = 2
	EventType_EVENT_TASK_COMPLETED     EventType = 3
	EventType_EVENT_FINDING_NEW        EventType = 4
	EventType_EVENT_OPERATOR_JOINED    EventType = 5
	EventType_EVENT_OPERATOR_LEFT      EventType = 6
	EventType_EVENT_SIBLING_CONNECTED  EventType = 7
	EventType_EVENT_PLUGIN_LOADED      EventType = 8
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_AGENT_CONNECTED",
		1: "EVENT_AGENT_DISCONNECTED",
		2: "EVENT_TASK_STARTED",
		3: "EVENT_TASK_COMPLETED",
		4: "EVENT_FINDING_NEW",
		5: "EVENT_OPERATOR_JOINED",
		6: "EVENT_OPERATOR_LEFT",
		7: "EVENT_SIBLING_CONNECTED",
		8: "EVENT_PLUGIN_LOADED",
	}
	EventType_value = map[string]int32{
		"EVENT_AGENT_CONNECTED":    0,
		"EVENT_AGENT_DISCONNECTED": 1,
		"EVENT_TASK_STARTED":       2,
		"EVENT_TASK_COMPLETED":     3,
		"EVENT_FINDING_NEW":        4,
		"EVENT_OPERATOR_JOINED":    5,
		"EVENT_OPERATOR_LEFT":      6,
		"EVENT_SIBLING_CONNECTED":  7,
		"EVENT_PLUGIN_LOADED":      8,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_spectre_proto_enumTypes[3].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_spectre_proto_enumTypes[3]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{3}
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	RamBytes      int64                  `protobuf:"varint,6,opt,name=ram_bytes,json=ramBytes,proto3" json:"ram_bytes,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	TailscaleIp   string                 `protobuf:"bytes,8,opt,name=tailscale_ip,json=tailscaleIp,proto3" json:"tailscale_ip,omitempty"`
	NebulaIp      string                 `protobuf:"bytes,9,opt,name=nebula_ip,json=nebulaIp,proto3" json:"nebula_ip,omitempty"`
	Version       string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	Mode          AgentMode              `protobuf:"varint,11,opt,name=mode,proto3,enum=spectre.AgentMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_spectre_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *AgentInfo) GetRamBytes() int64 {
	if x != nil {
		return x.RamBytes
	}
	return 0
}

func (x *AgentInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentInfo) GetTailscaleIp() string {
	if x != nil {
		return x.TailscaleIp
	}
	return ""
}

func (x *AgentInfo) GetNebulaIp() string {
	if x != nil {
		return x.NebulaIp
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetMode() AgentMode {
	if x != nil {
		return x.Mode
	}
	return AgentMode_AGENT_MODE_UNSPECIFIED
}

type BeaconConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SleepSeconds  int64                  `protobuf:"varint,1,opt,name=sleep_seconds,json=sleepSeconds,proto3" json:"sleep_seconds,omitempty"`
	JitterPct     float64                `protobuf:"fixed64,2,opt,name=jitter_pct,json=jitterPct,proto3" json:"jitter_pct,omitempty"`
	KillDateUnix  int64                  `protobuf:"varint,3,opt,name=kill_date_unix,json=killDateUnix,proto3" json:"kill_date_unix,omitempty"`
	ProfileName   string                 `protobuf:"bytes,4,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconConfig) Reset() {
	*x = BeaconConfig{}
	mi := &file_spectre_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconConfig) ProtoMessage() {}

func (x *BeaconConfig) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconConfig.ProtoReflect.Descriptor instead.
func (*BeaconConfig) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{1}
}

func (x *BeaconConfig) GetSleepSeconds() int64 {
	if x != nil {
		return x.SleepSeconds
	}
	return 0
}

func (x *BeaconConfig) GetJitterPct() float64 {
	if x != nil {
		return x.JitterPct
	}
	return 0
}

func (x *BeaconConfig) GetKillDateUnix() int64 {
	if x != nil {
		return x.KillDateUnix
	}
	return 0
}

func (x *BeaconConfig) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

type MalleableProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	UriPath       string                 `protobuf:"bytes,3,opt,name=uri_path,json=uriPath,proto3" json:"uri_path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SleepMask     string                 `protobuf:"bytes,5,opt,name=sleep_mask,json=sleepMask,proto3" json:"sleep_mask,omitempty"`
	UseSsl        bool                   `protobuf:"varint,6,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MalleableProfile) Reset() {
	*x = MalleableProfile{}
	mi := &file_spectre_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MalleableProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MalleableProfile) ProtoMessage() {}

func (x *MalleableProfile) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MalleableProfile.ProtoReflect.Descriptor instead.
func (*MalleableProfile) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{2}
}

func (x *MalleableProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MalleableProfile) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *MalleableProfile) GetUriPath() string {
	if x != nil {
		return x.UriPath
	}
	return ""
}

func (x *MalleableProfile) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *MalleableProfile) GetSleepMask() string {
	if x != nil {
		return x.SleepMask
	}
	return ""
}

func (x *MalleableProfile) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

type AgentMetrics struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"` // keep existing
	CpuPct    float32                `protobuf:"fixed32,3,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	MemPct    float32                `protobuf:"fixed32,4,opt,name=mem_pct,json=memPct,proto3" json:"mem_pct,omitempty"`
	DiskPct   float32                `protobuf:"fixed32,5,opt,name=disk_pct,json=diskPct,proto3" json:"disk_pct,omitempty"`
	Load_1M   float32                `protobuf:"fixed32,6,opt,name=load_1m,json=load1m,proto3" json:"load_1m,omitempty"`
	Timestamp int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Mode      AgentMode              `protobuf:"varint,8,opt,name=mode,proto3,enum=spectre.AgentMode" json:"mode,omitempty"`
	// Registration fields (populated on first connect, can be empty on subsequent heartbeats)
	Hostname      string   `protobuf:"bytes,9,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string   `protobuf:"bytes,10,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string   `protobuf:"bytes,11,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuCores      int32    `protobuf:"varint,12,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	RamBytes      int64    `protobuf:"varint,13,opt,name=ram_bytes,json=ramBytes,proto3" json:"ram_bytes,omitempty"`
	Tags          []string `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	TailscaleIp   string   `protobuf:"bytes,15,opt,name=tailscale_ip,json=tailscaleIp,proto3" json:"tailscale_ip,omitempty"`
	NebulaIp      string   `protobuf:"bytes,16,opt,name=nebula_ip,json=nebulaIp,proto3" json:"nebula_ip,omitempty"`
	Version       string   `protobuf:"bytes,17,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetrics) Reset() {
	*x = AgentMetrics{}
	mi := &file_spectre_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetrics) ProtoMessage() {}

func (x *AgentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetrics.ProtoReflect.Descriptor instead.
func (*AgentMetrics) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMetrics) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMetrics) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentMetrics) GetCpuPct() float32 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *AgentMetrics) GetMemPct() float32 {
	if x != nil {
		return x.MemPct
	}
	return 0
}

func (x *AgentMetrics) GetDiskPct() float32 {
	if x != nil {
		return x.DiskPct
	}
	return 0
}

func (x *AgentMetrics) GetLoad_1M() float32 {
	if x != nil {
		return x.Load_1M
	}
	return 0
}

func (x *AgentMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentMetrics) GetMode() AgentMode {
	if x != nil {
		return x.Mode
	}
	return AgentMode_AGENT_MODE_UNSPECIFIED
}

func (x *AgentMetrics) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentMetrics) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentMetrics) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentMetrics) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *AgentMetrics) GetRamBytes() int64 {
	if x != nil {
		return x.RamBytes
	}
	return 0
}

func (x *AgentMetrics) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentMetrics) GetTailscaleIp() string {
	if x != nil {
		return x.TailscaleIp
	}
	return ""
}

func (x *AgentMetrics) GetNebulaIp() string {
	if x != nil {
		return x.NebulaIp
	}
	return ""
}

func (x *AgentMetrics) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          TaskType               `protobuf:"varint,3,opt,name=type,proto3,enum=spectre.TaskType" json:"type,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	TimeoutSec    int64                  `protobuf:"varint,5,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	OperatorId    string                 `protobuf:"bytes,6,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_spectre_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{4}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_EXEC
}

func (x *TaskRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TaskRequest) GetTimeoutSec() int64 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *TaskRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *TaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TaskOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	IsStderr      bool                   `protobuf:"varint,4,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	IsDone        bool                   `protobuf:"varint,5,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
	ExitCode      int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Structured    string                 `protobuf:"bytes,8,opt,name=structured,proto3" json:"structured,omitempty"`
	OutType       TaskOutputType         `protobuf:"varint,9,opt,name=out_type,json=outType,proto3,enum=spectre.TaskOutputType" json:"out_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	mi := &file_spectre_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{5}
}

func (x *TaskOutput) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOutput) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskOutput) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *TaskOutput) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

func (x *TaskOutput) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *TaskOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskOutput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TaskOutput) GetStructured() string {
	if x != nil {
		return x.Structured
	}
	return ""
}

func (x *TaskOutput) GetOutType() TaskOutputType {
	if x != nil {
		return x.OutType
	}
	return TaskOutputType_OUTPUT_RAW
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FindingId     string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostIp        string                 `protobuf:"bytes,4,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Severity      string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Detail        string                 `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`
	CvssScore     float32                `protobuf:"fixed32,9,opt,name=cvss_score,json=cvssScore,proto3" json:"cvss_score,omitempty"`
	CveRefs       []string               `protobuf:"bytes,10,rep,name=cve_refs,json=cveRefs,proto3" json:"cve_refs,omitempty"`
	RawRequest    string                 `protobuf:"bytes,11,opt,name=raw_request,json=rawRequest,proto3" json:"raw_request,omitempty"`
	RawResponse   string                 `protobuf:"bytes,12,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"`
	Module        string                 `protobuf:"bytes,13,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_spectre_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{6}
}

func (x *Finding) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *Finding) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Finding) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Finding) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *Finding) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Finding) GetCvssScore() float32 {
	if x != nil {
		return x.CvssScore
	}
	return 0
}

func (x *Finding) GetCveRefs() []string {
	if x != nil {
		return x.CveRefs
	}
	return nil
}

func (x *Finding) GetRawRequest() string {
	if x != nil {
		return x.RawRequest
	}
	return ""
}

func (x *Finding) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

func (x *Finding) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type DefenderRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,4,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefenderRule) Reset() {
	*x = DefenderRule{}
	mi := &file_spectre_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefenderRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefenderRule) ProtoMessage() {}

func (x *DefenderRule) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefenderRule.ProtoReflect.Descriptor instead.
func (*DefenderRule) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{7}
}

func (x *DefenderRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DefenderRule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *DefenderRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DefenderRule) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

type ValidateCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Type          TaskType               `protobuf:"varint,2,opt,name=type,proto3,enum=spectre.TaskType" json:"type,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	TargetAgent   string                 `protobuf:"bytes,4,opt,name=target_agent,json=targetAgent,proto3" json:"target_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCommandRequest) Reset() {
	*x = ValidateCommandRequest{}
	mi := &file_spectre_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCommandRequest) ProtoMessage() {}

func (x *ValidateCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCommandRequest.ProtoReflect.Descriptor instead.
func (*ValidateCommandRequest) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateCommandRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *ValidateCommandRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_EXEC
}

func (x *ValidateCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ValidateCommandRequest) GetTargetAgent() string {
	if x != nil {
		return x.TargetAgent
	}
	return ""
}

type ValidateCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Warning       string                 `protobuf:"bytes,2,opt,name=warning,proto3" json:"warning,omitempty"`
	BlockReason   string                 `protobuf:"bytes,3,opt,name=block_reason,json=blockReason,proto3" json:"block_reason,omitempty"`
	MatchedRuleId string                 `protobuf:"bytes,4,opt,name=matched_rule_id,json=matchedRuleId,proto3" json:"matched_rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCommandResponse) Reset() {
	*x = ValidateCommandResponse{}
	mi := &file_spectre_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCommandResponse) ProtoMessage() {}

func (x *ValidateCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCommandResponse.ProtoReflect.Descriptor instead.
func (*ValidateCommandResponse) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateCommandResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ValidateCommandResponse) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *ValidateCommandResponse) GetBlockReason() string {
	if x != nil {
		return x.BlockReason
	}
	return ""
}

func (x *ValidateCommandResponse) GetMatchedRuleId() string {
	if x != nil {
		return x.MatchedRuleId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=spectre.EventType" json:"type,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OperatorId    string                 `protobuf:"bytes,6,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_spectre_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_AGENT_CONNECTED
}

func (x *Event) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

type TaskAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Received      bool                   `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAck) Reset() {
	*x = TaskAck{}
	mi := &file_spectre_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAck) ProtoMessage() {}

func (x *TaskAck) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAck.ProtoReflect.Descriptor instead.
func (*TaskAck) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{11}
}

func (x *TaskAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type BeaconCheckIn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Metrics        *AgentMetrics          `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	CompletedTasks []*TaskOutput          `protobuf:"bytes,3,rep,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BeaconCheckIn) Reset() {
	*x = BeaconCheckIn{}
	mi := &file_spectre_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconCheckIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconCheckIn) ProtoMessage() {}

func (x *BeaconCheckIn) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconCheckIn.ProtoReflect.Descriptor instead.
func (*BeaconCheckIn) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{12}
}

func (x *BeaconCheckIn) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BeaconCheckIn) GetMetrics() *AgentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *BeaconCheckIn) GetCompletedTasks() []*TaskOutput {
	if x != nil {
		return x.CompletedTasks
	}
	return nil
}

type BeaconResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PendingTasks  []*TaskRequest         `protobuf:"bytes,1,rep,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	Config        *BeaconConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconResponse) Reset() {
	*x = BeaconResponse{}
	mi := &file_spectre_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconResponse) ProtoMessage() {}

func (x *BeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconResponse.ProtoReflect.Descriptor instead.
func (*BeaconResponse) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{13}
}

func (x *BeaconResponse) GetPendingTasks() []*TaskRequest {
	if x != nil {
		return x.PendingTasks
	}
	return nil
}

func (x *BeaconResponse) GetConfig() *BeaconConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_spectre_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          TaskType               `protobuf:"varint,2,opt,name=type,proto3,enum=spectre.TaskType" json:"type,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	TargetAgents  []string               `protobuf:"bytes,4,rep,name=target_agents,json=targetAgents,proto3" json:"target_agents,omitempty"`
	TargetTags    []string               `protobuf:"bytes,5,rep,name=target_tags,json=targetTags,proto3" json:"target_tags,omitempty"`
	TimeoutSec    int64                  `protobuf:"varint,6,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	OperatorId    string                 `protobuf:"bytes,7,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	SkipDefender  bool                   `protobuf:"varint,8,opt,name=skip_defender,json=skipDefender,proto3" json:"skip_defender,omitempty"`
	Payload       []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_spectre_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{15}
}

func (x *DispatchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DispatchRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_EXEC
}

func (x *DispatchRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *DispatchRequest) GetTargetAgents() []string {
	if x != nil {
		return x.TargetAgents
	}
	return nil
}

func (x *DispatchRequest) GetTargetTags() []string {
	if x != nil {
		return x.TargetTags
	}
	return nil
}

func (x *DispatchRequest) GetTimeoutSec() int64 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *DispatchRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *DispatchRequest) GetSkipDefender() bool {
	if x != nil {
		return x.SkipDefender
	}
	return false
}

func (x *DispatchRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DispatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskIds         []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	AgentCount      int32                  `protobuf:"varint,2,opt,name=agent_count,json=agentCount,proto3" json:"agent_count,omitempty"`
	DefenderWarning string                 `protobuf:"bytes,3,opt,name=defender_warning,json=defenderWarning,proto3" json:"defender_warning,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_spectre_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{16}
}

func (x *DispatchResponse) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *DispatchResponse) GetAgentCount() int32 {
	if x != nil {
		return x.AgentCount
	}
	return 0
}

func (x *DispatchResponse) GetDefenderWarning() string {
	if x != nil {
		return x.DefenderWarning
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_spectre_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{17}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_spectre_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{18}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_spectre_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{19}
}

func (x *GetSessionsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_spectre_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{20}
}

func (x *GetSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FindingCount  int32                  `protobuf:"varint,6,opt,name=finding_count,json=findingCount,proto3" json:"finding_count,omitempty"`
	TaskCount     int32                  `protobuf:"varint,7,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_spectre_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{21}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SessionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SessionInfo) GetFindingCount() int32 {
	if x != nil {
		return x.FindingCount
	}
	return 0
}

func (x *SessionInfo) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

type GetFindingsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SeverityFilter string                 `protobuf:"bytes,2,opt,name=severity_filter,json=severityFilter,proto3" json:"severity_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFindingsRequest) Reset() {
	*x = GetFindingsRequest{}
	mi := &file_spectre_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFindingsRequest) ProtoMessage() {}

func (x *GetFindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFindingsRequest.ProtoReflect.Descriptor instead.
func (*GetFindingsRequest) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{22}
}

func (x *GetFindingsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetFindingsRequest) GetSeverityFilter() string {
	if x != nil {
		return x.SeverityFilter
	}
	return ""
}

type GetFindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFindingsResponse) Reset() {
	*x = GetFindingsResponse{}
	mi := &file_spectre_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFindingsResponse) ProtoMessage() {}

func (x *GetFindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spectre_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFindingsResponse.ProtoReflect.Descriptor instead.
func (*GetFindingsResponse) Descriptor() ([]byte, []int) {
	return file_spectre_proto_rawDescGZIP(), []int{23}
}

func (x *GetFindingsResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

var File_spectre_proto protoreflect.FileDescriptor

const file_spectre_proto_rawDesc = "" +
	"\n" +
	"\rspectre.proto\x12\aspectre\"\xb6\x02\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tram_bytes\x18\x06 \x01(\x03R\bramBytes\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12!\n" +
	"\ftailscale_ip\x18\b \x01(\tR\vtailscaleIp\x12\x1b\n" +
	"\tnebula_ip\x18\t \x01(\tR\bnebulaIp\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\x12&\n" +
	"\x04mode\x18\v \x01(\x0e2\x12.spectre.AgentModeR\x04mode\"\x9b\x01\n" +
	"\fBeaconConfig\x12#\n" +
	"\rsleep_seconds\x18\x01 \x01(\x03R\fsleepSeconds\x12\x1d\n" +
	"\n" +
	"jitter_pct\x18\x02 \x01(\x01R\tjitterPct\x12$\n" +
	"\x0ekill_date_unix\x18\x03 \x01(\x03R\fkillDateUnix\x12!\n" +
	"\fprofile_name\x18\x04 \x01(\tR\vprofileName\"\x96\x02\n" +
	"\x10MalleableProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x19\n" +
	"\buri_path\x18\x03 \x01(\tR\auriPath\x12@\n" +
	"\aheaders\x18\x04 \x03(\v2&.spectre.MalleableProfile.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"sleep_mask\x18\x05 \x01(\tR\tsleepMask\x12\x17\n" +
	"\ause_ssl\x18\x06 \x01(\bR\x06useSsl\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x03\n" +
	"\fAgentMetrics\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x17\n" +
	"\acpu_pct\x18\x03 \x01(\x02R\x06cpuPct\x12\x17\n" +
	"\amem_pct\x18\x04 \x01(\x02R\x06memPct\x12\x19\n" +
	"\bdisk_pct\x18\x05 \x01(\x02R\adiskPct\x12\x17\n" +
	"\aload_1m\x18\x06 \x01(\x02R\x06load1m\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12&\n" +
	"\x04mode\x18\b \x01(\x0e2\x12.spectre.AgentModeR\x04mode\x12\x1a\n" +
	"\bhostname\x18\t \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\n" +
	" \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\v \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_cores\x18\f \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tram_bytes\x18\r \x01(\x03R\bramBytes\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12!\n" +
	"\ftailscale_ip\x18\x0f \x01(\tR\vtailscaleIp\x12\x1b\n" +
	"\tnebula_ip\x18\x10 \x01(\tR\bnebulaIp\x12\x18\n" +
	"\aversion\x18\x11 \x01(\tR\aversion\"\xdc\x01\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.spectre.TaskTypeR\x04type\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x1f\n" +
	"\vtimeout_sec\x18\x05 \x01(\x03R\n" +
	"timeoutSec\x12\x1f\n" +
	"\voperator_id\x18\x06 \x01(\tR\n" +
	"operatorId\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"\x9b\x02\n" +
	"\n" +
	"TaskOutput\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tis_stderr\x18\x04 \x01(\bR\bisStderr\x12\x17\n" +
	"\ais_done\x18\x05 \x01(\bR\x06isDone\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"structured\x18\b \x01(\tR\n" +
	"structured\x122\n" +
	"\bout_type\x18\t \x01(\x0e2\x17.spectre.TaskOutputTypeR\aoutType\"\xef\x02\n" +
	"\aFinding\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_ip\x18\x04 \x01(\tR\x06hostIp\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x16\n" +
	"\x06detail\x18\b \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"cvss_score\x18\t \x01(\x02R\tcvssScore\x12\x19\n" +
	"\bcve_refs\x18\n" +
	" \x03(\tR\acveRefs\x12\x1f\n" +
	"\vraw_request\x18\v \x01(\tR\n" +
	"rawRequest\x12!\n" +
	"\fraw_response\x18\f \x01(\tR\vrawResponse\x12\x16\n" +
	"\x06module\x18\r \x01(\tR\x06module\"y\n" +
	"\fDefenderRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x04 \x01(\bR\tisBlocked\"\x97\x01\n" +
	"\x16ValidateCommandRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.spectre.TaskTypeR\x04type\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12!\n" +
	"\ftarget_agent\x18\x04 \x01(\tR\vtargetAgent\"\x98\x01\n" +
	"\x17ValidateCommandResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x18\n" +
	"\awarning\x18\x02 \x01(\tR\awarning\x12!\n" +
	"\fblock_reason\x18\x03 \x01(\tR\vblockReason\x12&\n" +
	"\x0fmatched_rule_id\x18\x04 \x01(\tR\rmatchedRuleId\"\xbe\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.spectre.EventTypeR\x04type\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\voperator_id\x18\x06 \x01(\tR\n" +
	"operatorId\">\n" +
	"\aTaskAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\bR\breceived\"\x99\x01\n" +
	"\rBeaconCheckIn\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12/\n" +
	"\ametrics\x18\x02 \x01(\v2\x15.spectre.AgentMetricsR\ametrics\x12<\n" +
	"\x0fcompleted_tasks\x18\x03 \x03(\v2\x13.spectre.TaskOutputR\x0ecompletedTasks\"z\n" +
	"\x0eBeaconResponse\x129\n" +
	"\rpending_tasks\x18\x01 \x03(\v2\x14.spectre.TaskRequestR\fpendingTasks\x12-\n" +
	"\x06config\x18\x02 \x01(\v2\x15.spectre.BeaconConfigR\x06config\"3\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\"\xb2\x02\n" +
	"\x0fDispatchRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.spectre.TaskTypeR\x04type\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12#\n" +
	"\rtarget_agents\x18\x04 \x03(\tR\ftargetAgents\x12\x1f\n" +
	"\vtarget_tags\x18\x05 \x03(\tR\n" +
	"targetTags\x12\x1f\n" +
	"\vtimeout_sec\x18\x06 \x01(\x03R\n" +
	"timeoutSec\x12\x1f\n" +
	"\voperator_id\x18\a \x01(\tR\n" +
	"operatorId\x12#\n" +
	"\rskip_defender\x18\b \x01(\bR\fskipDefender\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\"y\n" +
	"\x10DispatchResponse\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\x12\x1f\n" +
	"\vagent_count\x18\x02 \x01(\x05R\n" +
	"agentCount\x12)\n" +
	"\x10defender_warning\x18\x03 \x01(\tR\x0fdefenderWarning\"\x13\n" +
	"\x11ListAgentsRequest\"@\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.spectre.AgentInfoR\x06agents\"9\n" +
	"\x12GetSessionsRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\"G\n" +
	"\x13GetSessionsResponse\x120\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.spectre.SessionInfoR\bsessions\"\xd3\x01\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12#\n" +
	"\rfinding_count\x18\x06 \x01(\x05R\ffindingCount\x12\x1d\n" +
	"\n" +
	"task_count\x18\a \x01(\x05R\ttaskCount\"\\\n" +
	"\x12GetFindingsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fseverity_filter\x18\x02 \x01(\tR\x0eseverityFilter\"C\n" +
	"\x13GetFindingsResponse\x12,\n" +
	"\bfindings\x18\x01 \x03(\v2\x10.spectre.FindingR\bfindings*V\n" +
	"\tAgentMode\x12\x1a\n" +
	"\x16AGENT_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AGENT_MODE_SESSION\x10\x01\x12\x15\n" +
	"\x11AGENT_MODE_BEACON\x10\x02*\xbe\x01\n" +
	"\bTaskType\x12\r\n" +
	"\tTASK_EXEC\x10\x00\x12\x16\n" +
	"\x12TASK_SPECTRE_RECON\x10\x01\x12\x15\n" +
	"\x11TASK_SPECTRE_SCAN\x10\x02\x12\x15\n" +
	"\x11TASK_SPECTRE_FUZZ\x10\x03\x12\x18\n" +
	"\x14TASK_SPECTRE_EXPLOIT\x10\x04\x12\x0f\n" +
	"\vTASK_PLUGIN\x10\x05\x12\x0f\n" +
	"\vTASK_UPLOAD\x10\x06\x12\x11\n" +
	"\rTASK_DOWNLOAD\x10\a\x12\x0e\n" +
	"\n" +
	"TASK_SHELL\x10\b*W\n" +
	"\x0eTaskOutputType\x12\x0e\n" +
	"\n" +
	"OUTPUT_RAW\x10\x00\x12\x12\n" +
	"\x0eOUTPUT_FINDING\x10\x01\x12\x10\n" +
	"\fOUTPUT_TABLE\x10\x02\x12\x0f\n" +
	"\vOUTPUT_FILE\x10\x03*\xf7\x01\n" +
	"\tEventType\x12\x19\n" +
	"\x15EVENT_AGENT_CONNECTED\x10\x00\x12\x1c\n" +
	"\x18EVENT_AGENT_DISCONNECTED\x10\x01\x12\x16\n" +
	"\x12EVENT_TASK_STARTED\x10\x02\x12\x18\n" +
	"\x14EVENT_TASK_COMPLETED\x10\x03\x12\x15\n" +
	"\x11EVENT_FINDING_NEW\x10\x04\x12\x19\n" +
	"\x15EVENT_OPERATOR_JOINED\x10\x05\x12\x17\n" +
	"\x13EVENT_OPERATOR_LEFT\x10\x06\x12\x1b\n" +
	"\x17EVENT_SIBLING_CONNECTED\x10\a\x12\x17\n" +
	"\x13EVENT_PLUGIN_LOADED\x10\b2\xc5\x01\n" +
	"\fAgentService\x12:\n" +
	"\aConnect\x12\x15.spectre.AgentMetrics\x1a\x14.spectre.TaskRequest(\x010\x01\x12=\n" +
	"\x10StreamTaskOutput\x12\x13.spectre.TaskOutput\x1a\x10.spectre.TaskAck(\x010\x01\x12:\n" +
	"\aCheckIn\x12\x16.spectre.BeaconCheckIn\x1a\x17.spectre.BeaconResponse2\xc1\x03\n" +
	"\x0fOperatorService\x128\n" +
	"\tSubscribe\x12\x19.spectre.SubscribeRequest\x1a\x0e.spectre.Event0\x01\x12C\n" +
	"\fDispatchTask\x12\x18.spectre.DispatchRequest\x1a\x19.spectre.DispatchResponse\x12E\n" +
	"\n" +
	"ListAgents\x12\x1a.spectre.ListAgentsRequest\x1a\x1b.spectre.ListAgentsResponse\x12T\n" +
	"\x0fValidateCommand\x12\x1f.spectre.ValidateCommandRequest\x1a .spectre.ValidateCommandResponse\x12H\n" +
	"\vGetSessions\x12\x1b.spectre.GetSessionsRequest\x1a\x1c.spectre.GetSessionsResponse\x12H\n" +
	"\vGetFindings\x12\x1b.spectre.GetFindingsRequest\x1a\x1c.spectre.GetFindingsResponseB%Z#github.com/sbu/spectre-c2/pkg/protob\x06proto3"

var (
	file_spectre_proto_rawDescOnce sync.Once
	file_spectre_proto_rawDescData []byte
)

func file_spectre_proto_rawDescGZIP() []byte {
	file_spectre_proto_rawDescOnce.Do(func() {
		file_spectre_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spectre_proto_rawDesc), len(file_spectre_proto_rawDesc)))
	})
	return file_spectre_proto_rawDescData
}

var file_spectre_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_spectre_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_spectre_proto_goTypes = []any{
	(AgentMode)(0),                  // 0: spectre.AgentMode
	(TaskType)(0),                   // 1: spectre.TaskType
	(TaskOutputType)(0),             // 2: spectre.TaskOutputType
	(EventType)(0),                  // 3: spectre.EventType
	(*AgentInfo)(nil),               // 4: spectre.AgentInfo
	(*BeaconConfig)(nil),            // 5: spectre.BeaconConfig
	(*MalleableProfile)(nil),        // 6: spectre.MalleableProfile
	(*AgentMetrics)(nil),            // 7: spectre.AgentMetrics
	(*TaskRequest)(nil),             // 8: spectre.TaskRequest
	(*TaskOutput)(nil),              // 9: spectre.TaskOutput
	(*Finding)(nil),                 // 10: spectre.Finding
	(*DefenderRule)(nil),            // 11: spectre.DefenderRule
	(*ValidateCommandRequest)(nil),  // 12: spectre.ValidateCommandRequest
	(*ValidateCommandResponse)(nil), // 13: spectre.ValidateCommandResponse
	(*Event)(nil),                   // 14: spectre.Event
	(*TaskAck)(nil),                 // 15: spectre.TaskAck
	(*BeaconCheckIn)(nil),           // 16: spectre.BeaconCheckIn
	(*BeaconResponse)(nil),          // 17: spectre.BeaconResponse
	(*SubscribeRequest)(nil),        // 18: spectre.SubscribeRequest
	(*DispatchRequest)(nil),         // 19: spectre.DispatchRequest
	(*DispatchResponse)(nil),        // 20: spectre.DispatchResponse
	(*ListAgentsRequest)(nil),       // 21: spectre.ListAgentsRequest
	(*ListAgentsResponse)(nil),      // 22: spectre.ListAgentsResponse
	(*GetSessionsRequest)(nil),      // 23: spectre.GetSessionsRequest
	(*GetSessionsResponse)(nil),     // 24: spectre.GetSessionsResponse
	(*SessionInfo)(nil),             // 25: spectre.SessionInfo
	(*GetFindingsRequest)(nil),      // 26: spectre.GetFindingsRequest
	(*GetFindingsResponse)(nil),     // 27: spectre.GetFindingsResponse
	nil,                             // 28: spectre.MalleableProfile.HeadersEntry
}
var file_spectre_proto_depIdxs = []int32{
	0,  // 0: spectre.AgentInfo.mode:type_name -> spectre.AgentMode
	28, // 1: spectre.MalleableProfile.headers:type_name -> spectre.MalleableProfile.HeadersEntry
	0,  // 2: spectre.AgentMetrics.mode:type_name -> spectre.AgentMode
	1,  // 3: spectre.TaskRequest.type:type_name -> spectre.TaskType
	2,  // 4: spectre.TaskOutput.out_type:type_name -> spectre.TaskOutputType
	1,  // 5: spectre.ValidateCommandRequest.type:type_name -> spectre.TaskType
	3,  // 6: spectre.Event.type:type_name -> spectre.EventType
	7,  // 7: spectre.BeaconCheckIn.metrics:type_name -> spectre.AgentMetrics
	9,  // 8: spectre.BeaconCheckIn.completed_tasks:type_name -> spectre.TaskOutput
	8,  // 9: spectre.BeaconResponse.pending_tasks:type_name -> spectre.TaskRequest
	5,  // 10: spectre.BeaconResponse.config:type_name -> spectre.BeaconConfig
	1,  // 11: spectre.DispatchRequest.type:type_name -> spectre.TaskType
	4,  // 12: spectre.ListAgentsResponse.agents:type_name -> spectre.AgentInfo
	25, // 13: spectre.GetSessionsResponse.sessions:type_name -> spectre.SessionInfo
	10, // 14: spectre.GetFindingsResponse.findings:type_name -> spectre.Finding
	7,  // 15: spectre.AgentService.Connect:input_type -> spectre.AgentMetrics
	9,  // 16: spectre.AgentService.StreamTaskOutput:input_type -> spectre.TaskOutput
	16, // 17: spectre.AgentService.CheckIn:input_type -> spectre.BeaconCheckIn
	18, // 18: spectre.OperatorService.Subscribe:input_type -> spectre.SubscribeRequest
	19, // 19: spectre.OperatorService.DispatchTask:input_type -> spectre.DispatchRequest
	21, // 20: spectre.OperatorService.ListAgents:input_type -> spectre.ListAgentsRequest
	12, // 21: spectre.OperatorService.ValidateCommand:input_type -> spectre.ValidateCommandRequest
	23, // 22: spectre.OperatorService.GetSessions:input_type -> spectre.GetSessionsRequest
	26, // 23: spectre.OperatorService.GetFindings:input_type -> spectre.GetFindingsRequest
	8,  // 24: spectre.AgentService.Connect:output_type -> spectre.TaskRequest
	15, // 25: spectre.AgentService.StreamTaskOutput:output_type -> spectre.TaskAck
	17, // 26: spectre.AgentService.CheckIn:output_type -> spectre.BeaconResponse
	14, // 27: spectre.OperatorService.Subscribe:output_type -> spectre.Event
	20, // 28: spectre.OperatorService.DispatchTask:output_type -> spectre.DispatchResponse
	22, // 29: spectre.OperatorService.ListAgents:output_type -> spectre.ListAgentsResponse
	13, // 30: spectre.OperatorService.ValidateCommand:output_type -> spectre.ValidateCommandResponse
	24, // 31: spectre.OperatorService.GetSessions:output_type -> spectre.GetSessionsResponse
	27, // 32: spectre.OperatorService.GetFindings:output_type -> spectre.GetFindingsResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_spectre_proto_init() }
func file_spectre_proto_init() {
	if File_spectre_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spectre_proto_rawDesc), len(file_spectre_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_spectre_proto_goTypes,
		DependencyIndexes: file_spectre_proto_depIdxs,
		EnumInfos:         file_spectre_proto_enumTypes,
		MessageInfos:      file_spectre_proto_msgTypes,
	}.Build()
	File_spectre_proto = out.File
	file_spectre_proto_goTypes = nil
	file_spectre_proto_depIdxs = nil
}
